server:
  port: '8083'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pavi@123
    url: jdbc:mysql://localhost:3306/shoppingcart
    username: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: user-details-application
    
razorpay:
  api:
    key: rzp_test_zwbn0zujMSBacP
    secret: 3NQVFQlFUTspB5JcEIiAKDkG